### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by zot** [probonopd/Emacs.AppImage#10]
I'm getting this error when I try to run Emacs:

```
/tmp/.mount_Emacs-arD6eA/AppRun: line 11: /tmp/.mount_Emacs-arD6eA/usr/bin/emacs*.wrapper: No such file or directory
```

**Comment by probonopd** [comment]
I can reproduce this. Is hopefully fixed by https://github.com/probonopd/Emacs.AppImage/commit/b43f68f727e81e45ddb065147e6b019052063755.

**Comment by zot** [comment]
I'm still getting the "No such file or directory" error with the latest I just downloaded
```
Emacs-26.2.glibc2.17-x86_64_5a370fe59a8aef79b685b8f24ee426ff.AppImage
```

**Comment by probonopd** [comment]
Next build should work.

**Comment by zot** [comment]
I'll test it when it's available!

**Comment by zot** [comment]
How long until the new build is out there?

**Comment by probonopd** [comment]
There was some build issue. https://travis-ci.org/probonopd/Emacs.AppImage/builds/568527384 should hopefully build successfully now.

**Comment by zot** [comment]
Woohoo! Now I can switch back to using the AppImage version! It works!
